### ISSUE TITLE
Nuxt vite failed to write output  file 

### ISSUE THREAD

**Issue by silvesterwali** [nuxt/vite#10] opened 2021-02-25 22:13 UTC
hi all . i just installed fresh nuxt and add nuxt vite but  i got error like  below .

 ERROR  Client compiled with errors: The following dependencies are imported but could not be resolved:                  06:05:17  

  nuxt_plugin_plugin_4ccce809 (imported by C:/Users/sabana-code/documents/programing/vitenuxt/.nuxt/index.js)
  nuxt_plugin_plugin_4885f88b (imported by C:/Users/sabana-code/documents/programing/vitenuxt/.nuxt/index.js)

  nuxt_plugin_plugin_4ccce809 (imported by C:/Users/sabana-code/documents/programing/vitenuxt/.nuxt/index.js)
  nuxt_plugin_plugin_4885f88b (imported by C:/Users/sabana-code/documents/programing/vitenuxt/.nuxt/index.js)

error: Failed to write to output file: open C:\Users\pimp\documents\programing\vitenuxt\node_modules\.vite\temp\server.js: The system cannot find the path specified.

**Comment by pi0** [comment] 2021-02-25 22:14
Hi. This is a duplicate of #3. Will be fixed soon for supporting plugins :)

**Closed by pi0** 2021-02-25 22:14 UTC

**Comment by pi0** [comment] 2021-02-25 22:29
Fixed in 0.0.3

**Comment by silvesterwali** [comment] 2021-02-25 23:59
thanks @pi0 hope this will help
