### ISSUE TITLE
Nuxt components support

### ISSUE THREAD

**Issue by danielroe** [nuxt/vite#12] opened 2021-02-25 22:57 UTC
https://github.com/nuxt/components/pull/157

**Comment by pi0** [comment] 2021-02-25 23:29
I think it would be better finding a solution for root cause. There are many more plugins dont have default export. It might be fixed with a rollup plugin

**Closed** 2021-02-25 23:30 UTC

**Comment by nathanchase** [comment] 2021-02-26 03:22
> I think it would be better finding a solution for root cause. There are many more plugins dont have default export. It might be fixed with a rollup plugin

Perhaps https://github.com/TeleworkInc/rollup-plugin-export-default ?

**Comment by pi0** [comment] 2021-02-26 09:29
@nathanchase Yes i'm looking for similar way. That plugin is using `renderChunk` which is too late for vite.
